name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use your preferred Node.js version

    - name: Install dependencies
      run: npm install  # Use yarn or another package manager if needed

    - name: Build the project
      run: npm run build  # Run your build command (vite build or other)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: build  # The build folder generated after the build process
