name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/bun-actions/setup@v1
      with:
        bun-version: '1.1.29'  # Use the version of Bun you want

    - name: Install dependencies
      run: bun install  # Use bun to install dependencies

    - name: Build the project
      run: bun run build  # Run your build command using Bun

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: build  # The build folder generated after the build process
